version: "3"
services:
  github-actions-web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    image: github-actions-web
    container_name: github-actions-web
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html